const products = [
  {
    '_id': '1',
    'name': 'Coffee Bros Light Roast',
    'image': '/images/coffee_bros_light_roast.jpg',
    'description': 'Light roast brewed whole coffee whole bean.',
    'brand': 'Coffee Bros',
    'category': 'Coffee',
    'price': 13.99,
    'countInStock': 10,
    'rating': 0,
    'numReviews': 0,
  },
  {
    '_id': '2',
    'name': 'Coffee Bros Medium Roast',
    'image': '/images/coffee_bros_medium_roast.jpg',
    'description': 'Medium roast brewed coffee whole bean.',
    'brand': 'Coffee Bros',
    'category': 'Coffee',
    'price': 13.99,
    'countInStock': 7,
    'rating': 2.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Coffee Bros Dark Roast',
    'image': '/images/coffee_bros_dark_roast.jpg',
    'description': 'Dark roast brewed coffee beans whole bean.',
    'brand': 'Coffee Bros',
    'category': 'Coffee',
    'price': 13.99,
    'countInStock': 5,
    'rating': 1.5,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Coffee Bros Costa Rican Roast',
    'image': '/images/coffee_bros_costa_rica_roast.jpg',
    'description': 'Costa Rica brewed coffee beans whole bean single origin.',
    'brand': 'Coffee Bros',
    'category': 'Coffee',
    'price': 13.99,
    'countInStock': 19,
    'rating': .5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'Coffee Bros Espresso',
    'image': '/images/coffee_bros_espresso.jpg',
    'description': 'Espresso whole beans from Columbia and Ethopia. The flavor has notes of vanilla, strawberry, and sugar cane.',
    'brand': 'Coffee Bros',
    'category': 'Espresso',
    'price': 13.99,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Coffee Bros Holiday Roast',
    'image': '/images/coffee_bros_holiday_roast.jpg',
    'description': 'Seasonal Holiday Blend whole bean coffee. Beans sourced from Costa Rica and Brazil. Has flavor has notes of cooked berry, cocoa, and wine.',
    'brand': 'Coffee Bros',
    'category': 'Coffee',
    'price': 13.99,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '7',
    'name': 'Starbucks Blonde Espresso',
    'image': '/images/starbucks_blonde_espresso.jpg',
    'description': 'Blonde espresso beans in whole bean form.',
    'brand': 'Starbucks',
    'category': 'Espresso',
    'price': 14.99,
    'countInStock': 14,
    'rating': 4.5,
    'numReviews': 6,
  },
  {
    '_id': '8',
    'name': 'Starbucks Veranda Blonde Roast',
    'image': '/images/starbucks_blonde_roast.jpg',
    'description': 'Blonde whole bean Arabica coffee.',
    'brand': 'Starbucks',
    'category': 'Coffee',
    'price': 14.99,
    'countInStock': 13,
    'rating': 3.0,
    'numReviews': 3,
  },
  {
    '_id': '9',
    'name': 'Starbucks Dark Espresso',
    'image': '/images/starbucks_dark_espresso.jpg',
    'description': 'Ground dark roast esspresso beans.',
    'brand': 'Starbucks',
    'category': 'Espresso',
    'price': 14.99,
    'countInStock': 4,
    'rating': 3.5,
    'numReviews': 27,
  },
  {
    '_id': '10',
    'name': 'Starbucks Decaf Espresso',
    'image': '/images/starbucks_decaf_espresso.jpg',
    'description': 'Decaffinated whole bean dark roast espresso beans.',
    'brand': 'Starbucks',
    'category': 'Espresso',
    'price': 14.99,
    'countInStock': 7,
    'rating': 2.5,
    'numReviews': 5,
  },
  {
    '_id': '11',
    'name': 'Starbucks Decaf Pikes Place',
    'image': '/images/starbucks_decaf_pikes_place.jpg',
    'description': 'Decaf Pikes Place medium roast whole bean coffee.',
    'brand': 'Starbucks',
    'category': 'Coffee',
    'price': 14.99,
    'countInStock': 2,
    'rating': 2,
    'numReviews': 14,
  },
  {
    '_id': '12',
    'name': 'Starbucks Decaf Verona Roast',
    'image': '/images/starbucks_decaf_verona_roast.jpg',
    'description': 'Ground dark roast Verona 100% Arabica coffee beans.',
    'brand': 'Starbucks',
    'category': 'Coffee',
    'price': 14.99,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 8,
  },
  {
    '_id': '13',
    'name': 'Starbucks Dark Roast Espresso',
    'image': '/images/starbucks_espresso.jpg',
    'description': 'Whole bean dark roast espresso.',
    'brand': 'Starbucks',
    'category': 'Espresso',
    'price': 14.99,
    'countInStock': 42,
    'rating': 4.5,
    'numReviews': 34,
  },
  {
    '_id': '14',
    'name': 'Starbucks French Roast',
    'image': '/images/starbucks_french_roast.jpg',
    'description': 'Whole bean dark French Roast coffee.',
    'brand': 'Starbucks',
    'category': 'Coffee',
    'price': 14.99,
    'countInStock': 17,
    'rating': 3.5,
    'numReviews': 3,
  },
  {
    '_id': '15',
    'name': 'Starbucks Holiday Roast',
    'image': '/images/starbucks_holiday_roast.jpg',
    'description': 'Seasonal holiday blend. 100% Arabica whole bean coffee.',
    'brand': 'Starbucks',
    'category': 'Coffee',
    'price': 14.99,
    'countInStock': 2,
    'rating': 2.5,
    'numReviews': 9,
  },
  {
    '_id': '16',
    'name': 'Starbucks Pikes Place Roast',
    'image': '/images/starbucks_pikes_place.jpg',
    'description': 'Medium blend whole bean 100% Arabica coffee.',
    'brand': 'Starbucks',
    'category': 'Coffee',
    'price': 14.99,
    'countInStock': 55,
    'rating': 5,
    'numReviews': 42,
  },
  {
    '_id': '17',
    'name': 'Starbucks Sumatra Roast',
    'image': '/images/starbucks_sumatra.jpg',
    'description': 'Dark roast whole bean coffee from Sumatra.',
    'brand': 'Starbucks',
    'category': 'Coffee',
    'price': 14.99,
    'countInStock': 17,
    'rating': 3.5,
    'numReviews': 16,
  },
  {
    '_id': '18',
    'name': 'Starbucks Verona Roast',
    'image': '/images/starbucks_verona.jpg',
    'description': 'Dark roast Cafe Verona whole bean coffee.',
    'brand': 'Starbucks',
    'category': 'Coffee',
    'price': 14.99,
    'countInStock': 0,
    'rating': 3,
    'numReviews': 4,
  },
]


export default products
